### ISSUE TITLE
ros_reach plugins can not be loaded from Python

### ISSUE THREAD

**Issue by SammyRamone** [ros-industrial/reach_ros2#13] opened 2023-06-23 11:47 UTC
REACH provides [Python bindings](https://github.com/ros-industrial/reach/blob/master/src/python/python_bindings.cpp) that allow to start a reach study from Python. This also workes fine for the simple test reach_study.yaml with the plugins from the reach package.
However, if a plugin from this repo is used (e.g. MoveItIKSolver), it will result in the following error:
`RuntimeError: Failed to find or load library: libreach_ros_plugins.so with error: Bad file descriptor`

I spend a couple of hours trying to debug this issue but still don't fully understand it. For me personally, it is not a problem as I just want to run a complete study. I can also achieve this by using `os.system()` and then calling the C++ executable. I just wanted to do a cleaner solution. Therefore, **I am not requesting a fix for this**, but rather putting it here in case someone else stumples in this issue.

What I tried
------------
1. I tried exporting the name of the ros_reach_plugins the default way (`export REACH_PLUGINS='reach_ros_plugins'`) and by giving the complete absolute path to the .so file. Both of these work when starting from C++ but not from python.
2. I tried writing a simple C++ executable (see below) which just tries to load a plugin. This worked (except MoveIt then complaining that it gets no parameters from ROS, which is fine).
3. Calling the C++ executable (see below) from Python using `os.system()`. This works (as expected).
4. Adding `sys.setdlopenflags(os.RTLD_NOW | os.RTLD_GLOBAL)` to the top of the python script, as some internet research suggested this as a solution for `dlopen()` issues with Python bindings. It did not change anything.
5. I started writing a dummy plugin package to do further tests (with and without extern), but I was not able to load this package from Python nor C++. This might be due to some error from my side. I stopped working on this, since I did not want to spend more time on this issue if I can get around it with the `os.system()` call.

Idea on why this is an issue
-----------------------------
Maybe the Python interface has a problem loading this shared library as it uses the externally defined singleton for the node instance. 
https://github.com/ros-industrial/reach_ros2/blob/84f6a1e5af618d8b056f7996fb1fba5a289efa0c/include/reach_ros/utils.h#L55C3-L57

This singleton is instantiated only in the executable.
https://github.com/ros-industrial/reach_ros2/blob/84f6a1e5af618d8b056f7996fb1fba5a289efa0c/src/reach_study_node.cpp#L35-L42
https://github.com/ros-industrial/reach_ros2/blob/84f6a1e5af618d8b056f7996fb1fba5a289efa0c/src/reach_study_node.cpp#L49C5-L51

When the plugin is loaded from Python, this code is not executed as it is only in the executable and not in the plugins. It is unclear for me how this could be resolved.

Context
--------
Python Code for trying to load a package (does result in the above mentioned error):
```
import yaml
from reach import PluginLoader
yaml_path = '/home/best_mr/ws_reach/src/reach/test/reach_study.yaml'
with open(yaml_path) as f:
    config = yaml.safe_load(f)

loader = PluginLoader()
loader.search_libraries_env = "REACH_PLUGINS"

ik_config = config['ik_solver']
factory = loader.createIKSolverFactoryInstance('MoveItIKSolver')
ik_solver = factory.create(ik_config)
```

C++ executable which also just loads a single IKSolver. This works when directly called from C++ (except the expected error from MoveIt about missing parameters).
```
#include <reach/reach_study.h>
#include <reach/utils.h>
#include <reach/plugin_utils.h>
#include <reach/interfaces/ik_solver.h>

#include <boost_plugin_loader/plugin_loader.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/filesystem.hpp>
#include <yaml-cpp/yaml.h>
#include <rclcpp/rclcpp.hpp>

namespace reach_ros
{
    namespace utils
    {
        // we need to do this since the node is specified as "extern" in the shared library
        rclcpp::Node::SharedPtr node;
    } // namespace utils
}

int main(int argc, char **argv)
{
    rclcpp::init(argc, argv);
    rclcpp::executors::MultiThreadedExecutor executor = rclcpp::executors::MultiThreadedExecutor();
    std::thread executor_thread(std::bind(&rclcpp::executors::MultiThreadedExecutor::spin, &executor));
    reach_ros::utils::node = std::make_shared<rclcpp::Node>(
        "reach_study_node",
        rclcpp::NodeOptions().allow_undeclared_parameters(true).automatically_declare_parameters_from_overrides(true));
    executor.add_node(reach_ros::utils::node);

    const YAML::Node &config = YAML::LoadFile("/home/best_mr/ws_reach/src/reach/test/reach_study.yaml");
    const YAML::Node &ik_config = config["ik_solver"];

    boost_plugin_loader::PluginLoader loader;
    std::vector<std::string> plugin_libraries;
    boost::split(loader.search_libraries, "reach_plugins", boost::is_any_of(":"), boost::token_compress_on);
    loader.search_libraries_env = "REACH_PLUGINS";
    auto factory = loader.createInstance<reach::IKSolverFactory>("MoveItIKSolver");
    reach::IKSolver::ConstPtr ik_solver = factory->create(ik_config);

    return 0;
}
```

Closing Remarks
-----------------
Maybe some better error message from the boost_plugin_loader could make things more clear. For example, when giving a wrong/non-existing library name it will show the same error message and thus it is not clear if the shared library is not found at all or if there is something wrong with it. It just seems to forward the error which is happening when attempting to load the library, but it might make sense to run more prechecks. Of course this would then be more of an issue for the boost_plugin_loader package 🤷‍♂️.
If someone has some other ideas, I would be willing to try to fix this issue. However, as stated above, it is not crucial for myself and I don't want to invest huge amounts of time on it.

**Comment by marip8** [comment] 2023-06-23 19:03
I've used the Python interface to run a reach study with the MoveIt-based plugins in `reach_ros` for an application a couple months back, so I'm fairly confident this can work without too many changes. I haven't tested it with ROS2 yet, so maybe there are some peculiarities about it that are causing the issues. I can check it out some time in the next few days. Maybe as a part of that I can make some another demo that fully uses Python so we can have it as a reference implementation

**Comment by marip8** [comment] 2023-06-24 04:31
I was able to successfully load plugins from `reach_ros` (ROS1), but I ran into the same issue loading plugins from a separate repository (`RuntimeError: Failed to find or load library: <my_custom_lib>.so with error: Bad file descriptor`).

This error comes from [here](https://github.com/tesseract-robotics/boost_plugin_loader/blob/d009f2bdbae2dd94c1ae32116ee1dbf1e98fb1a6/src/utils.cpp#L49-L51`) when the plugin loader is unable to load a library. Normally this exception gets caught [here](https://github.com/tesseract-robotics/boost_plugin_loader/blob/d009f2bdbae2dd94c1ae32116ee1dbf1e98fb1a6/include/boost_plugin_loader/plugin_loader.hpp#L137), but if the plugin is not found in any of the specified libraries, the exception gets thrown again from [this line](https://github.com/tesseract-robotics/boost_plugin_loader/blob/d009f2bdbae2dd94c1ae32116ee1dbf1e98fb1a6/include/boost_plugin_loader/plugin_loader.hpp#L145) as it is trying to print a more helpful error message. That message typically looks like this:

```
RuntimeError: Failed to create plugin instance 'CustomIKSolver' of type 'reach::IKSolverFactory'
Search Paths (including system folders)
Search Libraries:
    - libreach_plugins.so
    - libreach_ros_plugins.so
Available plugins of type 'reach::IKSolverFactory':
    - NoOpIKSolver
    - MoveItIKSolver
    - DiscretizedMoveItIKSolverFactory
```

I'm not entirely sure why the plugin loader is unable to load my custom library. I confirmed it exists in the same directory as `reach_plugins.so` and `reach_ros_plugins.so` and has the same permissions. I'll have to look into it a little more

**Comment by marip8** [comment] 2023-06-24 05:17
@Levi-Armstrong have you seen any strange behavior like this from `boost_plugin_loader` before?

**Comment by Levi-Armstrong** [comment] 2023-06-24 05:27
Yep, usually there is something missing for the .so, like a header or link library. If you write an executed which uses the underlying class that the plugin factory is trying to load the issue is quickly exposed.

**Comment by Levi-Armstrong** [comment] 2023-06-24 05:31
> Yep, usually there is something missing for the .so, like a header or link library. If you write an executable which uses the underlying class that the plugin factory is trying to load the issue is quickly exposed. 

Reading more this may not be directly related, but any time I have seen the original error this was the issue.

**Comment by SammyRamone** [comment] 2023-06-26 07:55
Thanks for the quick responses. I'm glad that you could reproduce the issue.

> I've used the Python interface to run a reach study with the MoveIt-based plugins in `reach_ros` for an application a couple months back, so I'm fairly confident this can work without too many changes. I haven't tested it with ROS2 yet, so maybe there are some peculiarities about it that are causing the issues. 

This would support my hypothesis about the to the `extern` node singelton. The ROS 1 plugins do not have this, as each process in ROS 1 automatically has a common node. 
One more idea that just came to my mind: Did you use catkin to build the ROS 1 package? I uses colcon for the ROS 2 package. Normally, it should not make a difference on this level, but it would be a difference between them.

> I can check it out some time in the next few days. Maybe as a part of that I can make some another demo that fully uses Python so we can have it as a reference implementation

That would generally be a good idea. I already have some experience using Python interfaces with C++, but it still took me a moment to understand how I can use this interface of REACH.

> I'm not entirely sure why the plugin loader is unable to load my custom library. I confirmed it exists in the same directory as reach_plugins.so and reach_ros_plugins.so and has the same permissions. I'll have to look into it a little more

This fits to the issue that I had when I tried to create another minimal dummy plugin library (without the `extern` node singleton). Did you build this custom library the same way that you did with the ROS 1 package (i.e. with catkin)?

Did you build both the ROS 1 and the ROS 2 version at the same time? For me, the ROS 2 package creates a `libreach_ros_plugins.so` file (without any "2"). It did not try the ROS 1 version (as I have no ROS 1 installation), but this could generally lead to some name collision issues.

**Comment by Levi-Armstrong** [comment] 2023-06-26 13:43
If the plugin is coming from a pure cmake package; does it have the colcon.pkg file which gets installed? This makes sure the environment gets set up properly for pure cmake packages.

**Comment by SammyRamone** [comment] 2023-06-26 14:22
> If the plugin is coming from a pure cmake package; does it have the colcon.pkg file which gets installed? This makes sure the environment gets set up properly for pure cmake packages.

I built both (the ROS 2 package and my dummy package) as typical ROS 2 packages (with ament_cmake). So I guess the colcon.pkg is not necessary.
I tested adding the colcon.pkg from the reach package to reach_ros and built it again. However, it did not change anything. As it is propably ignored when using ament_cmake.

**Comment by Levi-Armstrong** [comment] 2023-06-26 14:30
Has the custom plugin been exported using the macro in the cpp file?

**Comment by SammyRamone** [comment] 2023-06-26 14:47
> Has the custom plugin been exported using the macro in the cpp file? I assume it has if it works in ROS1 but wanted to double check.

Yes. It also works from calling it from C++, which should fail otherwise.

I uploaded the (dirty/hacky) dummy plugin package that I created [here](https://github.com/SammyRamone/dummy_c_plugins). So you can have a look, if it helps somehow. The package also contains an executable that I used to test if this package and the reach_ros package can be accessed via C++. The name is chosen kind of stupid, as it results in a libdummy_c_plugins_plugins.so 😅  This package compiles and creates the shared_library but I can not even call it from C++. The reach_ros2 package is callable from C++ but not from Python.

**Comment by Levi-Armstrong** [comment] 2023-06-26 15:03
Do you notice any differences in the environment variable `LD_LIBRARY_PATH` between ROS1 and ROS2?

**Comment by SammyRamone** [comment] 2023-06-26 15:10
Since I don't have ROS 1 running, I can't answer that (maybe @marip8 can chip in there). However, the plugins from the reach package (which is pure cmake) work and it has the same path. Here the relevant part of my `LD_LIBRARY_PATH`
`/home/best_mr/ws_reach/install/reach_ros/lib:/home/best_mr/ws_reach/install/dummy_c_plugins/lib:/home/best_mr/ws_reach/install/reach/lib`
These directories also each contains the corresponding `*_plugins.so` and the basis `*.so` (e.g. `libreach_ros_plugins.so` and `libreach_ros.so`)

**Comment by marip8** [comment] 2023-06-26 16:22
I don't think this is a problem with the plugin loader not finding the libraries. As I mentioned before, all of my `*_plugins.so` libraries exist in the same directory, and the plugin loader is able to load some of them (and I double checked the spelling of the one it wasn't able to load). I think there is a problem with the library itself that prevents it from being loaded, and the error returned by boost (`Bad file descriptor`) is just vague.

The `LD_LIBRARY_PATH` variable for my ROS1 system looks basically the same as ROS2: `/home/mripperger/ros/ws/devel/lib:/opt/ros/noetic/lib/x86_64-linux-gnu`

**Comment by Levi-Armstrong** [comment] 2023-06-26 16:28
If you run ldd on the library after sourcing ros2 workspace do you see any issues?

**Comment by marip8** [comment] 2023-06-26 16:29
> This would support my hypothesis about the to the extern node singelton. The ROS 1 plugins do not have this, as each process in ROS 1 automatically has a common node.

Possibly. I'm also having issues with the "normal" c++ code finding these custom ROS1 plugins (in addition to the Python interface), so I think the issue is more about the build of the library than the contents.


> One more idea that just came to my mind: Did you use catkin to build the ROS 1 package? I uses colcon for the ROS 2 package. Normally, it should not make a difference on this level, but it would be a difference between them.

> This fits to the issue that I had when I tried to create another minimal dummy plugin library (without the extern node singleton). Did you build this custom library the same way that you did with the ROS 1 package (i.e. with catkin)?

Yes, I did use `catkin`

> Did you build both the ROS 1 and the ROS 2 version at the same time? For me, the ROS 2 package creates a libreach_ros_plugins.so file (without any "2"). It did not try the ROS 1 version (as I have no ROS 1 installation), but this could generally lead to some name collision issues.

No. I don't think it's possible to successfully build both ROS1 and ROS2 interfaces in the same workspace at the same time. I've always built them in separate workspaces to avoid these sorts of conflicts

**Comment by marip8** [comment] 2023-06-26 17:05
I don't see any missing libraries when I run `ldd`. I do see quite a few undefined references when I run `nm -u -C <>_plugins.so` though:

<details>
    <summary>`nm -u -C ` output</summary>

```                 U __assert_fail@@GLIBC_2.2.5
                 U cos@@GLIBC_2.2.5
                 U __cxa_allocate_exception@@CXXABI_1.3
                 U __cxa_atexit@@GLIBC_2.2.5
                 U __cxa_begin_catch@@CXXABI_1.3
                 U __cxa_demangle@@CXXABI_1.3
                 U __cxa_end_catch@@CXXABI_1.3
                 w __cxa_finalize@@GLIBC_2.2.5
                 U __cxa_free_exception@@CXXABI_1.3
                 U __cxa_guard_acquire@@CXXABI_1.3
                 U __cxa_guard_release@@CXXABI_1.3
                 U __cxa_pure_virtual@@CXXABI_1.3
                 U __cxa_rethrow@@CXXABI_1.3
                 U __cxa_throw@@CXXABI_1.3
                 U __dynamic_cast@@CXXABI_1.3
                 U floor@@GLIBC_2.2.5
                 U free@@GLIBC_2.2.5
                 w __gmon_start__
                 U GOMP_parallel@@GOMP_4.0
                 U __gxx_personality_v0@@CXXABI_1.3
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U malloc@@GLIBC_2.2.5
                 U memcmp@@GLIBC_2.2.5
                 U memcpy@@GLIBC_2.14
                 U memmove@@GLIBC_2.2.5
                 U omp_get_max_threads@@OMP_1.0
                 U omp_get_num_threads@@OMP_1.0
                 U omp_get_thread_num@@OMP_1.0
                 U pow@@GLIBC_2.29
                 w __pthread_key_create
                 w pthread_mutex_lock@@GLIBC_2.2.5
                 w pthread_mutex_unlock@@GLIBC_2.2.5
                 U sin@@GLIBC_2.2.5
                 U sqrt@@GLIBC_2.2.5
                 U __stack_chk_fail@@GLIBC_2.4
                 U strcmp@@GLIBC_2.2.5
                 U strerror_r@@GLIBC_2.2.5
                 U strncpy@@GLIBC_2.2.5
                 U _Unwind_Resume@@GCC_3.0
                 U operator delete[](void*)@@GLIBCXX_3.4
                 U operator delete(void*)@@GLIBCXX_3.4
                 U operator delete(void*, unsigned long)@@CXXABI_1.3.9
                 U planning_scene::PlanningScene::processCollisionObjectMsg(moveit_msgs::CollisionObject_<std::allocator<void> > const&)
                 U interactive_markers::InteractiveMarkerServer::~InteractiveMarkerServer()
                 U ros::NodeHandle::~NodeHandle()
                 U ros::serialization::throwStreamOverrun()
                 U ros::console::initialize()
                 U ros::console::g_initialized
                 U ros::console::setLogLocationLevel(ros::console::LogLocation*, ros::console::levels::Level)
                 U ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)
                 U ros::console::checkLogLocationEnabled(ros::console::LogLocation*)
                 U ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, char const*, int, char const*, char const*, ...)
                 U ros::Publisher::~Publisher()
                 U YAML::InvalidNode::~InvalidNode()
                 U YAML::BadSubscript::~BadSubscript()
                 U YAML::BadConversion::~BadConversion()
                 U YAML::detail::memory::create_node()
                 U YAML::detail::node_data::empty_scalar[abi:cxx11]
                 U YAML::detail::node_data::mark_defined()
                 U YAML::detail::node_data::end()
                 U YAML::detail::node_data::begin()
                 U YAML::detail::node_data::set_null()
                 U YAML::convert<bool>::decode(YAML::Node const&, bool&)
                 U YAML::operator<<(std::ostream&, YAML::Node const&)
                 U reach::createFrame(Eigen::Matrix<float, 3, 1, 0, 3, 1> const&, Eigen::Matrix<float, 3, 1, 0, 3, 1> const&)
                 U moveit::planning_interface::getSharedRobotModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
                 U moveit::core::RobotState::getFrameTransform(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)
                 U moveit::core::RobotState::updateLinkTransforms()
                 U moveit::core::RobotState::setJointGroupPositions(moveit::core::JointModelGroup const*, double const*)
                 U moveit::core::RobotState::update(bool)
                 U moveit::core::RobotState::RobotState(std::shared_ptr<moveit::core::RobotModel const> const&)
                 U moveit::core::RobotState::~RobotState()
                 U reach_ros::ik::MoveItIKSolver::setTouchLinks(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
                 U reach_ros::ik::MoveItIKSolver::COLLISION_OBJECT_NAME[abi:cxx11]
                 U reach_ros::ik::MoveItIKSolver::MoveItIKSolver(std::shared_ptr<moveit::core::RobotModel const>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double)
                 U reach_ros::utils::transcribeInputMap(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
                 U reach_ros::utils::initROS(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
                 U reach_ros::display::ROSDisplay::ROSDisplay(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, bool)
                 U operator new[](unsigned long)@@GLIBCXX_3.4
                 U planning_scene::PlanningScene::getPlanningSceneMsg(moveit_msgs::PlanningScene_<std::allocator<void> >&) const
                 U ros::Publisher::Impl::isValid() const
                 U ros::Publisher::publish(boost::function<ros::SerializedMessage ()> const&, ros::SerializedMessage&) const
                 U YAML::detail::node_data::size() const
                 U moveit::core::RobotModel::getJointModelGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
                 U moveit::core::RobotState::getJacobian(moveit::core::JointModelGroup const*, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&) const
                 U reach_ros::ik::MoveItIKSolver::getJointNames[abi:cxx11]() const
                 U reach_ros::ik::MoveItIKSolver::getKinematicBaseFrame[abi:cxx11]() const
                 U reach_ros::ik::MoveItIKSolver::solveIK(Eigen::Transform<double, 3, 1, 0> const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > > const&) const
                 U reach_ros::display::ROSDisplay::showResults(std::vector<reach::ReachRecord, Eigen::aligned_allocator<reach::ReachRecord> > const&) const
                 U reach_ros::display::ROSDisplay::showEnvironment() const
                 U reach_ros::display::ROSDisplay::updateRobotPose(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > > const&) const
                 U reach_ros::display::ROSDisplay::showReachNeighborhood(std::map<unsigned long, reach::ReachRecord, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, reach::ReachRecord> > > const&) const
                 U std::runtime_error::what() const@@GLIBCXX_3.4
                 U std::_V2::error_category::_M_message[abi:cxx11](int) const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::data() const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::str() const@@GLIBCXX_3.4.21
                 U std::basic_ios<char, std::char_traits<char> >::eof() const@@GLIBCXX_3.4
                 U std::basic_ios<char, std::char_traits<char> >::operator bool() const@@GLIBCXX_3.4.21
                 U std::allocator<char>::allocator()@@GLIBCXX_3.4
                 U std::allocator<char>::~allocator()@@GLIBCXX_3.4
                 U std::allocator<char>::~allocator()@@GLIBCXX_3.4
                 U std::istream::operator>>(std::istream& (*)(std::istream&))@@GLIBCXX_3.4
                 U std::istream::operator>>(std::ios_base& (*)(std::ios_base&))@@GLIBCXX_3.4
                 U std::istream::operator>>(double&)@@GLIBCXX_3.4
                 U std::istream::operator>>(int&)@@GLIBCXX_3.4
                 U std::istream::operator>>(unsigned int&)@@GLIBCXX_3.4
                 U std::ostream::operator<<(int)@@GLIBCXX_3.4
                 U std::ostream::operator<<(unsigned int)@@GLIBCXX_3.4
                 U std::ostream::operator<<(unsigned long)@@GLIBCXX_3.4
                 U std::runtime_error::runtime_error(char const*)@@GLIBCXX_3.4.21
                 U std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::runtime_error::~runtime_error()@@GLIBCXX_3.4
                 U std::runtime_error::~runtime_error()@@GLIBCXX_3.4
                 U std::_V2::error_category::~error_category()@@GLIBCXX_3.4.21
                 U std::_V2::generic_category()@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_capacity(unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data()@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_set_length(unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char const*, char const*)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data(char*)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char const*)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@@GLIBCXX_3.4.26
                 U std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@@GLIBCXX_3.4.21
                 U std::ios_base::Init::Init()@@GLIBCXX_3.4
                 U std::ios_base::Init::~Init()@@GLIBCXX_3.4
                 U std::bad_alloc::~bad_alloc()@@GLIBCXX_3.4
                 U operator new(unsigned long)@@GLIBCXX_3.4
                 U std::__throw_bad_alloc()@@GLIBCXX_3.4
                 U std::_Rb_tree_decrement(std::_Rb_tree_node_base*)@@GLIBCXX_3.4
                 U std::_Rb_tree_increment(std::_Rb_tree_node_base const*)@@GLIBCXX_3.4
                 U std::__throw_logic_error(char const*)@@GLIBCXX_3.4
                 U std::__throw_length_error(char const*)@@GLIBCXX_3.4
                 U std::__throw_system_error(int)@@GLIBCXX_3.4.11
                 U std::__throw_out_of_range_fmt(char const*, ...)@@GLIBCXX_3.4.20
                 U std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)@@GLIBCXX_3.4
                 U std::basic_istream<char, std::char_traits<char> >& std::ws<char, std::char_traits<char> >(std::basic_istream<char, std::char_traits<char> >&)@@GLIBCXX_3.4
                 U std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)@@GLIBCXX_3.4
                 U typeinfo for bool@@CXXABI_1.3
                 U typeinfo for double@@CXXABI_1.3
                 U typeinfo for int@@CXXABI_1.3
                 U typeinfo for YAML::InvalidNode
                 U typeinfo for YAML::BadSubscript
                 U typeinfo for YAML::BadConversion
                 U typeinfo for YAML::Exception
                 U typeinfo for reach_ros::ik::MoveItIKSolver
                 U typeinfo for reach_ros::display::ROSDisplay
                 U typeinfo for std::_V2::error_category@@GLIBCXX_3.4.21
                 U typeinfo for std::runtime_error@@GLIBCXX_3.4
                 U typeinfo for std::bad_alloc@@GLIBCXX_3.4
                 U vtable for __cxxabiv1::__class_type_info@@CXXABI_1.3
                 U vtable for __cxxabiv1::__si_class_type_info@@CXXABI_1.3
                 U vtable for __cxxabiv1::__vmi_class_type_info@@CXXABI_1.3
                 U vtable for YAML::InvalidNode
                 U vtable for YAML::BadSubscript
                 U vtable for YAML::BadConversion
                 U vtable for YAML::RepresentationException
                 U vtable for YAML::Exception
                 U vtable for reach_ros::ik::MoveItIKSolver
                 U vtable for reach_ros::display::ROSDisplay
                 U vtable for std::_V2::error_category@@GLIBCXX_3.4.21
                 U vtable for std::bad_alloc@@GLIBCXX_3.4
                 U vtable for std::exception@@GLIBCXX_3.4

```
</details>

Everything builds fine though, so I'm not sure how to get rid of these

**Comment by Levi-Armstrong** [comment] 2023-06-26 17:21
Those typically will not show up until you use those libraries when linking. In the ros2 package I would create an executable which uses the object that the factory produces and see if you have any error show up.

**Comment by Levi-Armstrong** [comment] 2023-06-26 17:26
I actually don't see any undefined in what you posted. It is a lower case `u` which indicates undefined and not the capital `U`.

**Comment by marip8** [comment] 2023-06-26 18:38
> I actually don't see any undefined in what you posted. It is a lower case `u` which indicates undefined and not the capital `U`.

I think the capital `U` actually does represent undefined symbols. According to the [`nm` man page](https://www.linux.org/docs/man1/nm.html) the `-u` option shows all undefined references. But according to various posts, these undefined symbols can be provided by other dynamically linked libraries, so it's harder to tell if something is actually missing from the REACH libraries.

I'll make an executable per your suggestion and see what happens when I try to run it

**Comment by marip8** [comment] 2023-06-26 20:19
At least for the ROS1 plugins, it turns out that I was exporting the `reach_ros_plugins` library (with only the plugin definitions) to the catkin package rather than the underlying `reach_ros` library (with all of the plugin implementations), so my downstream custom plugins had undefined references to functions/classes in `reach_ros`, preventing the library from being opened.

**Comment by marip8** [comment] 2023-06-27 15:50
See #15 for a solution to this issue

**Comment by marip8** [comment] 2023-08-16 22:30
Closing; use of ROS2 plugins from Python should be fully supported as of #19 (tagged as version 1.2.0)

**Closed by marip8** 2023-08-16 22:30 UTC
